development: &default
  session_secret: '1234567890'
  site_url: 'http://localhost:3000'
  site_title: 'andyHu的家'
  site_motto: '为了爱我的和我爱的人而奋斗'
  site_description: 'andy个人网站'
  show_certification: true
  show_me_url: ''
  blog_search_ping: false
  google_cse: '007540752216561218107:cgbwg20yn_o'
  weibo_api_key: '1234567890'
  weibo_api_secret: '1234567890'
  weibo_redirect_uri: ''
  weibo_uid: '3197730713'
  weibo_uid_verifier: '6bd0aff2'

test: 
  <<: *default

production:
  <<: *default
  site_url: 'http://ml-china.org'
  blog_search_ping: true
